FROM golang:alpine as builder

WORKDIR /src

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o email-app ./cmd/email/

FROM alpine:latest

WORKDIR /root/

COPY . .

COPY --from=builder /src/email-app .

EXPOSE 8082

CMD ["./email-app"]
