FROM golang:alpine as builder

WORKDIR /src

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o session-app ./cmd/session/

FROM alpine:latest

WORKDIR /root/

COPY . .

COPY --from=builder /src/session-app .

EXPOSE 8081

CMD ["./session-app"]
