version: "3"
services:
  go-docker:
    build:
      context: .
      dockerfile: ./Dockerfile-server
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_NAME: ${PG_NAME}
    depends_on:
      - postgres
      - session
    ports:
      - "8080:8080"
    volumes:
      - ./:/server
      - ./avatars:/server/avatars

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres:/var/lib/postgresql/data


  redis:
    image: redis:latest
    container_name: "redis_container"
    environment:
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - ./sessions:/var/lib/redis

  session:
    build:
      context: .
      dockerfile: ./Dockerfile-session
    container_name: "dentistry_session"
    depends_on:
      - redis
    ports:
      - "8081:8081"
    volumes:
      - ./:/session

  email_microservice:
    build:
      context: .
      dockerfile: Dockerfile-email
    environment:
      MAIL_PASS: ${MAIL_PASS}
    container_name: "dentistry_email"
    depends_on:
      - session
    ports:
      - "8082:8082"
    volumes:
      - ./:/email
