// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: handler/email.proto

package handler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailCheckerClient is the client API for EmailChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailCheckerClient interface {
	SendEmail(ctx context.Context, in *EmailModel, opts ...grpc.CallOption) (*NothingSec, error)
}

type emailCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailCheckerClient(cc grpc.ClientConnInterface) EmailCheckerClient {
	return &emailCheckerClient{cc}
}

func (c *emailCheckerClient) SendEmail(ctx context.Context, in *EmailModel, opts ...grpc.CallOption) (*NothingSec, error) {
	out := new(NothingSec)
	err := c.cc.Invoke(ctx, "/handler.EmailChecker/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailCheckerServer is the server API for EmailChecker service.
// All implementations must embed UnimplementedEmailCheckerServer
// for forward compatibility
type EmailCheckerServer interface {
	SendEmail(context.Context, *EmailModel) (*NothingSec, error)
	mustEmbedUnimplementedEmailCheckerServer()
}

// UnimplementedEmailCheckerServer must be embedded to have forward compatible implementations.
type UnimplementedEmailCheckerServer struct {
}

func (UnimplementedEmailCheckerServer) SendEmail(context.Context, *EmailModel) (*NothingSec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedEmailCheckerServer) mustEmbedUnimplementedEmailCheckerServer() {}

// UnsafeEmailCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailCheckerServer will
// result in compilation errors.
type UnsafeEmailCheckerServer interface {
	mustEmbedUnimplementedEmailCheckerServer()
}

func RegisterEmailCheckerServer(s grpc.ServiceRegistrar, srv EmailCheckerServer) {
	s.RegisterService(&EmailChecker_ServiceDesc, srv)
}

func _EmailChecker_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailCheckerServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/handler.EmailChecker/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailCheckerServer).SendEmail(ctx, req.(*EmailModel))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailChecker_ServiceDesc is the grpc.ServiceDesc for EmailChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "handler.EmailChecker",
	HandlerType: (*EmailCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _EmailChecker_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handler/email.proto",
}
